const roadmaps = [
	{
		title: "Web Development",
		description: "Frontend, Backend, and Full Stack Development",
		progress: 0,
		paths: ["HTML/CSS", "JavaScript", "React", "Node.js", "Databases"],
		color: "text-blue-500",
	},
	{
		title: "Data Structures and Algorithms",
		description: "Master programming and problem solving",
		progress: 0,
		paths: ["Arrays", "Linked Lists", "Trees", "Graphs", "Dynamic Programming"],
		color: "text-green-500",
	},
	{
		title: "Machine Learning",
		description: "AI, Deep Learning, and Data Science",
		progress: 0,
		paths: [
			"Python",
			"Statistics",
			"Neural Networks",
			"Computer Vision",
			"NLP",
		],
		color: "text-purple-500",
	},
	{
		title: "Mobile Development",
		description: "iOS, Android, and Cross-platform development",
		progress: 0,
		paths: ["React Native", "Flutter", "iOS", "Android", "Mobile Design"],
		color: "text-orange-500",
	},
	{
		title: "Backend Development",
		description: "Server-side programming and architecture",
		progress: 0,
		paths: ["APIs", "Databases", "Authentication", "Cloud", "DevOps"],
		color: "text-red-500",
	},
	{
		title: "Database Engineering",
		description: "Database design, optimization, and management",
		progress: 0,
		paths: ["SQL", "NoSQL", "Data Modeling", "Performance", "Security"],
		color: "text-yellow-500",
	},
];

const resources = {
	websites: [
		{
			title: "freeCodeCamp",
			description: "Learn to code with free interactive tutorials",
			url: "https://www.freecodecamp.org",
			tags: ["Programming", "Web Development", "Free"],
			rating: 4.8,
		},
		{
			title: "LeetCode",
			description: "Practice coding problems and prepare for interviews",
			url: "https://leetcode.com",
			tags: ["DSA", "Interview Prep", "Coding"],
			rating: 4.9,
		},
		{
			title: "MDN Web Docs",
			description: "Comprehensive web development documentation",
			url: "https://developer.mozilla.org",
			tags: ["Web Development", "Documentation", "Reference"],
			rating: 4.9,
		},
		{
			title: "Codecademy",
			description:
				"Interactive coding lessons in various programming languages",
			url: "https://www.codecademy.com",
			tags: ["Programming", "Interactive", "Multiple Languages"],
			rating: 4.7,
		},
		{
			title: "GitHub",
			description: "Version control and collaboration platform for developers",
			url: "https://github.com",
			tags: ["Git", "Open Source", "Collaboration"],
			rating: 4.9,
		},
		{
			title: "Stack Overflow",
			description: "Q&A community for programmers",
			url: "https://stackoverflow.com",
			tags: ["Programming", "Community", "Problem Solving"],
			rating: 4.8,
		},
		{
			title: "Dev.to",
			description: "Community of software developers sharing knowledge",
			url: "https://dev.to",
			tags: ["Blog", "Community", "Programming"],
			rating: 4.7,
		},
		{
			title: "CSS-Tricks",
			description: "Tips, tricks, and techniques for web developers",
			url: "https://css-tricks.com",
			tags: ["CSS", "Web Development", "Frontend"],
			rating: 4.8,
		},
		{
			title: "Kaggle",
			description: "Platform for data science and machine learning",
			url: "https://www.kaggle.com",
			tags: ["Data Science", "Machine Learning", "Competitions"],
			rating: 4.8,
		},
		{
			title: "HackerRank",
			description: "Coding challenges and competitions",
			url: "https://www.hackerrank.com",
			tags: ["Programming", "Practice", "Interviews"],
			rating: 4.7,
		},
	],
	youtube: [
		{
			title: "Traversy Media",
			description: "Web development tutorials and crash courses",
			url: "https://www.youtube.com/@TraversyMedia",
			tags: ["Web Development", "Tutorials", "Programming"],
			rating: 4.8,
		},
		{
			title: "freeCodeCamp",
			description: "In-depth programming courses and tutorials",
			url: "https://www.youtube.com/@freecodecamp",
			tags: ["Programming", "Courses", "Free"],
			rating: 4.9,
		},
		{
			title: "Tech With Tim",
			description: "Python programming and machine learning tutorials",
			url: "https://www.youtube.com/@TechWithTim",
			tags: ["Python", "Machine Learning", "Tutorials"],
			rating: 4.7,
		},
		{
			title: "Fireship",
			description: "Quick, practical web development tutorials",
			url: "https://www.youtube.com/@Fireship",
			tags: ["Web Development", "Quick Tips", "Modern Tech"],
			rating: 4.9,
		},
		{
			title: "The Net Ninja",
			description: "Full stack web development tutorials",
			url: "https://www.youtube.com/@NetNinja",
			tags: ["Web Development", "Full Stack", "Tutorials"],
			rating: 4.8,
		},
		{
			title: "Academind",
			description: "In-depth programming courses and tutorials",
			url: "https://www.youtube.com/@academind",
			tags: ["Programming", "Web Development", "Courses"],
			rating: 4.8,
		},
		{
			title: "Coding Train",
			description: "Creative coding tutorials and challenges",
			url: "https://www.youtube.com/@TheCodingTrain",
			tags: ["Creative Coding", "JavaScript", "P5.js"],
			rating: 4.9,
		},
		{
			title: "Programming with Mosh",
			description: "Professional programming tutorials",
			url: "https://www.youtube.com/@programmingwithmosh",
			tags: ["Programming", "Software Development", "Tutorials"],
			rating: 4.8,
		},
		{
			title: "Sentdex",
			description: "Python programming and machine learning",
			url: "https://www.youtube.com/@sentdex",
			tags: ["Python", "Machine Learning", "Data Science"],
			rating: 4.7,
		},
		{
			title: "Web Dev Simplified",
			description: "Web development concepts explained simply",
			url: "https://www.youtube.com/@WebDevSimplified",
			tags: ["Web Development", "JavaScript", "Tutorials"],
			rating: 4.8,
		},
	],
	books: [
		{
			title: "Clean Code",
			description: "A Handbook of Agile Software Craftsmanship",
			author: "Robert C. Martin",
			url: "https://www.amazon.fr/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882",
			tags: ["Programming", "Best Practices", "Software Development"],
			rating: 4.7,
		},
		{
			title: "Cracking the Coding Interview",
			description: "189 Programming Questions & Solutions",
			author: "Gayle Laakmann McDowell",
			url: "https://www.amazon.fr/Cracking-Coding-Interview-Programming-Questions/dp/0984782850",
			tags: ["Interview Prep", "DSA", "Career"],
			rating: 4.8,
		},
		{
			title: "You Don't Know JS",
			description: "Deep dive into JavaScript",
			author: "Kyle Simpson",
			url: "https://www.amazon.fr/You-Dont-Know-JS-Scope/dp/1449335586",
			tags: ["JavaScript", "Web Development", "Programming"],
			rating: 4.8,
		},
		{
			title: "Design Patterns",
			description: "Elements of Reusable Object-Oriented Software",
			author: "Gang of Four",
			url: "https://www.amazon.fr/Design-Patterns-Elements-Reusable-Object-Oriented/dp/0201633612",
			tags: ["Design Patterns", "Software Architecture", "OOP"],
			rating: 4.7,
		},
		{
			title: "The Pragmatic Programmer",
			description: "Your Journey to Mastery",
			author: "Andrew Hunt, David Thomas",
			url: "https://www.amazon.fr/Pragmatic-Programmer-journey-mastery-Anniversary/dp/0135957052",
			tags: ["Programming", "Best Practices", "Career"],
			rating: 4.8,
		},
		{
			title: "Introduction to Algorithms",
			description: "Comprehensive guide to algorithms",
			author: "Thomas H. Cormen",
			url: "https://www.amazon.fr/Introduction-Algorithms-3rd-MIT-Press/dp/0262033844",
			tags: ["Algorithms", "Computer Science", "DSA"],
			rating: 4.9,
		},
	],
};

const courses = [
	{
		title: "Complete Web Development Bootcamp",
		description: "Learn full-stack web development from scratch",
		image:
			"https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop&q=60",
		instructor: "Dr. Angela Yu",
		duration: "63 hours",
		students: "850K+",
		rating: 4.8,
		tags: ["Web Development", "Full Stack", "JavaScript"],
		platform: "Udemy",
		price: "$89.99",
		url: "https://www.udemy.com/course/the-complete-web-development-bootcamp",
	},
	{
		title: "Machine Learning Specialization",
		description: "Master machine learning concepts and practical applications",
		image:
			"https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&auto=format&fit=crop&q=60",
		instructor: "Andrew Ng",
		duration: "80 hours",
		students: "1M+",
		rating: 4.9,
		tags: ["Machine Learning", "AI", "Python"],
		platform: "Coursera",
		price: "$49/month",
		url: "https://www.coursera.org/specializations/machine-learning-introduction",
	},
	{
		title: "Data Structures and Algorithms",
		description: "Comprehensive guide to DSA with Java",
		image:
			"https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=800&auto=format&fit=crop&q=60",
		instructor: "Tim Buchalka",
		duration: "55 hours",
		students: "450K+",
		rating: 4.7,
		tags: ["DSA", "Java", "Programming"],
		platform: "Udemy",
		price: "$79.99",
		url: "https://www.udemy.com/course/data-structures-and-algorithms-deep-dive-using-java",
	},
	{
		title: "React - The Complete Guide",
		description: "Master modern React with Redux and Next.js",
		image:
			"https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&auto=format&fit=crop&q=60",
		instructor: "Maximilian Schwarzmüller",
		duration: "48 hours",
		students: "700K+",
		rating: 4.8,
		tags: ["React", "Web Development", "JavaScript"],
		platform: "Udemy",
		price: "$89.99",
		url: "https://www.udemy.com/course/react-the-complete-guide-incl-redux",
	},
	{
		title: "Python for Data Science",
		description: "Learn Python programming for data analysis",
		image:
			"https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=60",
		instructor: "Jose Portilla",
		duration: "42 hours",
		students: "550K+",
		rating: 4.7,
		tags: ["Python", "Data Science", "Analytics"],
		platform: "Udemy",
		price: "$84.99",
		url: "https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp",
	},
	{
		title: "AWS Certified Solutions Architect",
		description: "Prepare for AWS certification with hands-on labs",
		image:
			"https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=60",
		instructor: "Stephane Maarek",
		duration: "35 hours",
		students: "400K+",
		rating: 4.8,
		tags: ["AWS", "Cloud", "DevOps"],
		platform: "Udemy",
		price: "$94.99",
		url: "https://www.udemy.com/course/aws-certified-solutions-architect-associate",
	},
	{
		title: "iOS & Swift - The Complete iOS App Development",
		description: "Build iOS apps with Swift and UIKit",
		image:
			"https://images.unsplash.com/photo-1621839673705-6617adf9e890?w=800&auto=format&fit=crop&q=60",
		instructor: "Angela Yu",
		duration: "55 hours",
		students: "200K+",
		rating: 4.8,
		tags: ["iOS", "Swift", "Mobile Development"],
		platform: "Udemy",
		price: "$89.99",
		url: "https://www.udemy.com/course/ios-13-app-development-bootcamp",
	},
	{
		title: "The Complete JavaScript Course",
		description: "Master JavaScript with modern ES6+ features",
		image:
			"https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800&auto=format&fit=crop&q=60",
		instructor: "Jonas Schmedtmann",
		duration: "69 hours",
		students: "600K+",
		rating: 4.8,
		tags: ["JavaScript", "Web Development", "ES6"],
		platform: "Udemy",
		price: "$89.99",
		url: "https://www.udemy.com/course/the-complete-javascript-course",
	},
	{
		title: "Flutter & Dart - The Complete Guide",
		description: "Build native mobile apps for Android and iOS",
		image:
			"https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&auto=format&fit=crop&q=60",
		instructor: "Maximilian Schwarzmüller",
		duration: "45 hours",
		students: "150K+",
		rating: 4.7,
		tags: ["Flutter", "Dart", "Mobile Development"],
		platform: "Udemy",
		price: "$84.99",
		url: "https://www.udemy.com/course/learn-flutter-dart-to-build-ios-android-apps",
	},
	{
		title: "Deep Learning Specialization",
		description: "Master deep learning and neural networks",
		image:
			"https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?w=800&auto=format&fit=crop&q=60",
		instructor: "Andrew Ng",
		duration: "100 hours",
		students: "800K+",
		rating: 4.9,
		tags: ["Deep Learning", "AI", "Neural Networks"],
		platform: "Coursera",
		price: "$49/month",
		url: "https://www.coursera.org/specializations/deep-learning",
	},
];

const interviewContent = {
	technical: [
		{
			title: "Data Structures & Algorithms",
			description: "Master common DSA problems and patterns",
			topics: ["Arrays & Strings", "Trees & Graphs", "Dynamic Programming"],
			difficulty: "Medium",
			questions: 150,
		},
		{
			title: "System Design",
			description: "Learn to design scalable distributed systems",
			topics: ["Scalability", "Database Design", "Load Balancing"],
			difficulty: "Hard",
			questions: 50,
		},
		{
			title: "Web Development",
			description: "Frontend and backend interview questions",
			topics: ["React", "Node.js", "APIs", "Databases"],
			difficulty: "Medium",
			questions: 100,
		},
		{
			title: "Object-Oriented Programming",
			description: "OOP concepts and design patterns",
			topics: ["Classes & Objects", "Inheritance", "Polymorphism"],
			difficulty: "Medium",
			questions: 80,
		},
		{
			title: "Database Management",
			description: "SQL and NoSQL database concepts",
			topics: ["SQL Queries", "Indexing", "Normalization"],
			difficulty: "Medium",
			questions: 70,
		},
		{
			title: "Operating Systems",
			description: "Core OS concepts and principles",
			topics: ["Processes", "Memory Management", "File Systems"],
			difficulty: "Hard",
			questions: 60,
		},
		{
			title: "Network Programming",
			description: "Networking protocols and architecture",
			topics: ["TCP/IP", "HTTP/HTTPS", "WebSockets"],
			difficulty: "Medium",
			questions: 45,
		},
		{
			title: "Security Concepts",
			description: "Application security and best practices",
			topics: ["Authentication", "Encryption", "Web Security"],
			difficulty: "Hard",
			questions: 55,
		},
		{
			title: "Cloud Computing",
			description: "Cloud platforms and services",
			topics: ["AWS", "Azure", "Docker", "Kubernetes"],
			difficulty: "Medium",
			questions: 65,
		},
		{
			title: "Testing & Debugging",
			description: "Software testing methodologies",
			topics: ["Unit Testing", "Integration Testing", "Debugging"],
			difficulty: "Easy",
			questions: 40,
		},
	],
	behavioral: [
		{
			title: "Leadership & Teamwork",
			description: "STAR method responses for behavioral questions",
			topics: [
				"Conflict Resolution",
				"Team Collaboration",
				"Project Management",
			],
			questions: 30,
		},
		{
			title: "Problem Solving",
			description: "Demonstrate your analytical thinking",
			topics: ["Critical Thinking", "Decision Making", "Innovation"],
			questions: 25,
		},
		{
			title: "Cultural Fit",
			description: "Show alignment with company values",
			topics: ["Company Research", "Values Alignment", "Career Goals"],
			questions: 20,
		},
		{
			title: "Communication Skills",
			description: "Effective communication scenarios",
			topics: ["Presentation", "Written Communication", "Active Listening"],
			questions: 35,
		},
		{
			title: "Time Management",
			description: "Prioritization and organization",
			topics: ["Deadlines", "Multi-tasking", "Work-Life Balance"],
			questions: 28,
		},
		{
			title: "Adaptability",
			description: "Handling change and challenges",
			topics: ["Learning Agility", "Flexibility", "Growth Mindset"],
			questions: 22,
		},
		{
			title: "Initiative & Motivation",
			description: "Self-driven achievements",
			topics: ["Goal Setting", "Self-improvement", "Proactivity"],
			questions: 26,
		},
		{
			title: "Client Relations",
			description: "Customer service and stakeholder management",
			topics: ["Customer Focus", "Relationship Building", "Negotiation"],
			questions: 24,
		},
		{
			title: "Project Experience",
			description: "Discussing past projects and achievements",
			topics: ["Project Impact", "Challenges Overcome", "Lessons Learned"],
			questions: 32,
		},
		{
			title: "Career Development",
			description: "Professional growth and aspirations",
			topics: ["Career Planning", "Skill Development", "Industry Knowledge"],
			questions: 28,
		},
	],
	resume: [
		{
			title: "Resume Templates",
			description: "ATS-friendly templates for different roles",
			formats: ["Software Engineer", "Data Scientist", "Product Manager"],
			downloads: "10K+",
		},
		{
			title: "Resume Writing Guide",
			description: "Tips and best practices for crafting your resume",
			topics: ["Structure", "Action Words", "Achievements"],
			reads: "25K+",
		},
		{
			title: "Resume Review Checklist",
			description: "Ensure your resume stands out",
			topics: ["Format", "Content", "Keywords"],
			downloads: "15K+",
		},
		{
			title: "Technical Skills Section",
			description: "Showcase your technical expertise",
			topics: ["Skills Organization", "Proficiency Levels", "Keywords"],
			downloads: "12K+",
		},
		{
			title: "Project Descriptions",
			description: "How to describe your projects effectively",
			topics: ["Impact Metrics", "Technical Details", "Role Clarity"],
			reads: "18K+",
		},
		{
			title: "Work Experience Format",
			description: "Structure your work experience section",
			topics: ["Bullet Points", "Achievements", "Responsibilities"],
			downloads: "20K+",
		},
		{
			title: "Education Section Guide",
			description: "Highlight your educational background",
			topics: [
				"Degree Information",
				"Relevant Coursework",
				"Academic Achievements",
			],
			reads: "14K+",
		},
		{
			title: "Cover Letter Templates",
			description: "Matching cover letters for your resume",
			formats: ["Entry Level", "Senior Position", "Career Change"],
			downloads: "8K+",
		},
		{
			title: "Portfolio Integration",
			description: "Link your projects and portfolio",
			topics: ["GitHub Profile", "Personal Website", "Project Showcase"],
			reads: "16K+",
		},
		{
			title: "Resume Optimization",
			description: "Optimize for ATS and human readers",
			topics: ["ATS Keywords", "Formatting", "File Types"],
			downloads: "22K+",
		},
	],
};

export { roadmaps, resources, courses, interviewContent };
